# Generated by Django 5.1.3 on 2025-09-09 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedido', '0002_alter_pedido_dt_hora'),
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itempedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10)),
                ('total', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produto')),
            ],
        ),
    ]
