# Generated by Django 5.1.3 on 2025-08-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itempedido', '0003_alter_itempedido_preco_alter_itempedido_qtd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='qtd',
        ),
        migrations.AddField(
            model_name='itempedido',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
