# Generated by Django 5.1.3 on 2025-08-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itempedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1, editable=False, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=1, editable=False, max_digits=10),
            preserve_default=False,
        ),
    ]
