# Generated by Django 5.1.3 on 2025-09-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='dt_hora',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora do Pedido'),
        ),
    ]
